# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization_msg/LocAccelerationStd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import localization_msg.msg

class LocAccelerationStd(genpy.Message):
  _md5sum = "a32c28cbafd6527f52d23800ca583be9"
  _type = "localization_msg/LocAccelerationStd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 available
LocAccStdGlobal acc_std_global
LocAccStdLocal acc_std_local
================================================================================
MSG: localization_msg/LocAccStdGlobal
float64 std_ae
float64 std_an
float64 std_au
================================================================================
MSG: localization_msg/LocAccStdLocal
float64 std_ax
float64 std_ay
float64 std_az"""
  __slots__ = ['available','acc_std_global','acc_std_local']
  _slot_types = ['uint8','localization_msg/LocAccStdGlobal','localization_msg/LocAccStdLocal']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       available,acc_std_global,acc_std_local

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocAccelerationStd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.available is None:
        self.available = 0
      if self.acc_std_global is None:
        self.acc_std_global = localization_msg.msg.LocAccStdGlobal()
      if self.acc_std_local is None:
        self.acc_std_local = localization_msg.msg.LocAccStdLocal()
    else:
      self.available = 0
      self.acc_std_global = localization_msg.msg.LocAccStdGlobal()
      self.acc_std_local = localization_msg.msg.LocAccStdLocal()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.available, _x.acc_std_global.std_ae, _x.acc_std_global.std_an, _x.acc_std_global.std_au, _x.acc_std_local.std_ax, _x.acc_std_local.std_ay, _x.acc_std_local.std_az))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.acc_std_global is None:
        self.acc_std_global = localization_msg.msg.LocAccStdGlobal()
      if self.acc_std_local is None:
        self.acc_std_local = localization_msg.msg.LocAccStdLocal()
      end = 0
      _x = self
      start = end
      end += 49
      (_x.available, _x.acc_std_global.std_ae, _x.acc_std_global.std_an, _x.acc_std_global.std_au, _x.acc_std_local.std_ax, _x.acc_std_local.std_ay, _x.acc_std_local.std_az,) = _get_struct_B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.available, _x.acc_std_global.std_ae, _x.acc_std_global.std_an, _x.acc_std_global.std_au, _x.acc_std_local.std_ax, _x.acc_std_local.std_ay, _x.acc_std_local.std_az))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.acc_std_global is None:
        self.acc_std_global = localization_msg.msg.LocAccStdGlobal()
      if self.acc_std_local is None:
        self.acc_std_local = localization_msg.msg.LocAccStdLocal()
      end = 0
      _x = self
      start = end
      end += 49
      (_x.available, _x.acc_std_global.std_ae, _x.acc_std_global.std_an, _x.acc_std_global.std_au, _x.acc_std_local.std_ax, _x.acc_std_local.std_ay, _x.acc_std_local.std_az,) = _get_struct_B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B6d = None
def _get_struct_B6d():
    global _struct_B6d
    if _struct_B6d is None:
        _struct_B6d = struct.Struct("<B6d")
    return _struct_B6d
