# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization_msg/LocAcceleration.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import localization_msg.msg

class LocAcceleration(genpy.Message):
  _md5sum = "724325e8eb34f4183b9fd545647fdfc8"
  _type = "localization_msg/LocAcceleration"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 available
LocAccGlobal acceleration_global
LocAccLocal acceleration_local
================================================================================
MSG: localization_msg/LocAccGlobal
float64 ae
float64 an
float64 au
================================================================================
MSG: localization_msg/LocAccLocal
float64 ax
float64 ay
float64 az"""
  __slots__ = ['available','acceleration_global','acceleration_local']
  _slot_types = ['uint8','localization_msg/LocAccGlobal','localization_msg/LocAccLocal']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       available,acceleration_global,acceleration_local

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocAcceleration, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.available is None:
        self.available = 0
      if self.acceleration_global is None:
        self.acceleration_global = localization_msg.msg.LocAccGlobal()
      if self.acceleration_local is None:
        self.acceleration_local = localization_msg.msg.LocAccLocal()
    else:
      self.available = 0
      self.acceleration_global = localization_msg.msg.LocAccGlobal()
      self.acceleration_local = localization_msg.msg.LocAccLocal()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.available, _x.acceleration_global.ae, _x.acceleration_global.an, _x.acceleration_global.au, _x.acceleration_local.ax, _x.acceleration_local.ay, _x.acceleration_local.az))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.acceleration_global is None:
        self.acceleration_global = localization_msg.msg.LocAccGlobal()
      if self.acceleration_local is None:
        self.acceleration_local = localization_msg.msg.LocAccLocal()
      end = 0
      _x = self
      start = end
      end += 49
      (_x.available, _x.acceleration_global.ae, _x.acceleration_global.an, _x.acceleration_global.au, _x.acceleration_local.ax, _x.acceleration_local.ay, _x.acceleration_local.az,) = _get_struct_B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.available, _x.acceleration_global.ae, _x.acceleration_global.an, _x.acceleration_global.au, _x.acceleration_local.ax, _x.acceleration_local.ay, _x.acceleration_local.az))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.acceleration_global is None:
        self.acceleration_global = localization_msg.msg.LocAccGlobal()
      if self.acceleration_local is None:
        self.acceleration_local = localization_msg.msg.LocAccLocal()
      end = 0
      _x = self
      start = end
      end += 49
      (_x.available, _x.acceleration_global.ae, _x.acceleration_global.an, _x.acceleration_global.au, _x.acceleration_local.ax, _x.acceleration_local.ay, _x.acceleration_local.az,) = _get_struct_B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B6d = None
def _get_struct_B6d():
    global _struct_B6d
    if _struct_B6d is None:
        _struct_B6d = struct.Struct("<B6d")
    return _struct_B6d
