# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization_msg/LocOrientation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import localization_msg.msg

class LocOrientation(genpy.Message):
  _md5sum = "d51feb8932d7b17d92287bf94b778169"
  _type = "localization_msg/LocOrientation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 available
LocEuler euler_global
LocQuaternion quaternion_global
LocEuler euler_local
LocQuaternion quaternion_local
================================================================================
MSG: localization_msg/LocEuler
float64 roll
float64 pitch
float64 yaw
================================================================================
MSG: localization_msg/LocQuaternion
float64 w
float64 x
float64 y
float64 z"""
  __slots__ = ['available','euler_global','quaternion_global','euler_local','quaternion_local']
  _slot_types = ['uint8','localization_msg/LocEuler','localization_msg/LocQuaternion','localization_msg/LocEuler','localization_msg/LocQuaternion']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       available,euler_global,quaternion_global,euler_local,quaternion_local

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocOrientation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.available is None:
        self.available = 0
      if self.euler_global is None:
        self.euler_global = localization_msg.msg.LocEuler()
      if self.quaternion_global is None:
        self.quaternion_global = localization_msg.msg.LocQuaternion()
      if self.euler_local is None:
        self.euler_local = localization_msg.msg.LocEuler()
      if self.quaternion_local is None:
        self.quaternion_local = localization_msg.msg.LocQuaternion()
    else:
      self.available = 0
      self.euler_global = localization_msg.msg.LocEuler()
      self.quaternion_global = localization_msg.msg.LocQuaternion()
      self.euler_local = localization_msg.msg.LocEuler()
      self.quaternion_local = localization_msg.msg.LocQuaternion()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B14d().pack(_x.available, _x.euler_global.roll, _x.euler_global.pitch, _x.euler_global.yaw, _x.quaternion_global.w, _x.quaternion_global.x, _x.quaternion_global.y, _x.quaternion_global.z, _x.euler_local.roll, _x.euler_local.pitch, _x.euler_local.yaw, _x.quaternion_local.w, _x.quaternion_local.x, _x.quaternion_local.y, _x.quaternion_local.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.euler_global is None:
        self.euler_global = localization_msg.msg.LocEuler()
      if self.quaternion_global is None:
        self.quaternion_global = localization_msg.msg.LocQuaternion()
      if self.euler_local is None:
        self.euler_local = localization_msg.msg.LocEuler()
      if self.quaternion_local is None:
        self.quaternion_local = localization_msg.msg.LocQuaternion()
      end = 0
      _x = self
      start = end
      end += 113
      (_x.available, _x.euler_global.roll, _x.euler_global.pitch, _x.euler_global.yaw, _x.quaternion_global.w, _x.quaternion_global.x, _x.quaternion_global.y, _x.quaternion_global.z, _x.euler_local.roll, _x.euler_local.pitch, _x.euler_local.yaw, _x.quaternion_local.w, _x.quaternion_local.x, _x.quaternion_local.y, _x.quaternion_local.z,) = _get_struct_B14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B14d().pack(_x.available, _x.euler_global.roll, _x.euler_global.pitch, _x.euler_global.yaw, _x.quaternion_global.w, _x.quaternion_global.x, _x.quaternion_global.y, _x.quaternion_global.z, _x.euler_local.roll, _x.euler_local.pitch, _x.euler_local.yaw, _x.quaternion_local.w, _x.quaternion_local.x, _x.quaternion_local.y, _x.quaternion_local.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.euler_global is None:
        self.euler_global = localization_msg.msg.LocEuler()
      if self.quaternion_global is None:
        self.quaternion_global = localization_msg.msg.LocQuaternion()
      if self.euler_local is None:
        self.euler_local = localization_msg.msg.LocEuler()
      if self.quaternion_local is None:
        self.quaternion_local = localization_msg.msg.LocQuaternion()
      end = 0
      _x = self
      start = end
      end += 113
      (_x.available, _x.euler_global.roll, _x.euler_global.pitch, _x.euler_global.yaw, _x.quaternion_global.w, _x.quaternion_global.x, _x.quaternion_global.y, _x.quaternion_global.z, _x.euler_local.roll, _x.euler_local.pitch, _x.euler_local.yaw, _x.quaternion_local.w, _x.quaternion_local.x, _x.quaternion_local.y, _x.quaternion_local.z,) = _get_struct_B14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B14d = None
def _get_struct_B14d():
    global _struct_B14d
    if _struct_B14d is None:
        _struct_B14d = struct.Struct("<B14d")
    return _struct_B14d
