# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization_msg/LocVelocity.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import localization_msg.msg

class LocVelocity(genpy.Message):
  _md5sum = "a9f526371b70d001d1a3b75d8970bc2e"
  _type = "localization_msg/LocVelocity"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 available
LocVelGlobal velocity_global
LocVelLocal velocity_local
================================================================================
MSG: localization_msg/LocVelGlobal
float64 ve
float64 vn
float64 vu
================================================================================
MSG: localization_msg/LocVelLocal
float64 vx
float64 vy
float64 vz"""
  __slots__ = ['available','velocity_global','velocity_local']
  _slot_types = ['uint8','localization_msg/LocVelGlobal','localization_msg/LocVelLocal']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       available,velocity_global,velocity_local

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocVelocity, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.available is None:
        self.available = 0
      if self.velocity_global is None:
        self.velocity_global = localization_msg.msg.LocVelGlobal()
      if self.velocity_local is None:
        self.velocity_local = localization_msg.msg.LocVelLocal()
    else:
      self.available = 0
      self.velocity_global = localization_msg.msg.LocVelGlobal()
      self.velocity_local = localization_msg.msg.LocVelLocal()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.available, _x.velocity_global.ve, _x.velocity_global.vn, _x.velocity_global.vu, _x.velocity_local.vx, _x.velocity_local.vy, _x.velocity_local.vz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.velocity_global is None:
        self.velocity_global = localization_msg.msg.LocVelGlobal()
      if self.velocity_local is None:
        self.velocity_local = localization_msg.msg.LocVelLocal()
      end = 0
      _x = self
      start = end
      end += 49
      (_x.available, _x.velocity_global.ve, _x.velocity_global.vn, _x.velocity_global.vu, _x.velocity_local.vx, _x.velocity_local.vy, _x.velocity_local.vz,) = _get_struct_B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.available, _x.velocity_global.ve, _x.velocity_global.vn, _x.velocity_global.vu, _x.velocity_local.vx, _x.velocity_local.vy, _x.velocity_local.vz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.velocity_global is None:
        self.velocity_global = localization_msg.msg.LocVelGlobal()
      if self.velocity_local is None:
        self.velocity_local = localization_msg.msg.LocVelLocal()
      end = 0
      _x = self
      start = end
      end += 49
      (_x.available, _x.velocity_global.ve, _x.velocity_global.vn, _x.velocity_global.vu, _x.velocity_local.vx, _x.velocity_local.vy, _x.velocity_local.vz,) = _get_struct_B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B6d = None
def _get_struct_B6d():
    global _struct_B6d
    if _struct_B6d is None:
        _struct_B6d = struct.Struct("<B6d")
    return _struct_B6d
