# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization_msg/LocStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import localization_msg.msg

class LocStatus(genpy.Message):
  _md5sum = "e00652c44afdc23232e5217c17a7d02e"
  _type = "localization_msg/LocStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 available
LocStatusInfo status_info
================================================================================
MSG: localization_msg/LocStatusInfo
uint8 quality
uint64 common
uint64 extended
uint8 type"""
  __slots__ = ['available','status_info']
  _slot_types = ['uint8','localization_msg/LocStatusInfo']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       available,status_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.available is None:
        self.available = 0
      if self.status_info is None:
        self.status_info = localization_msg.msg.LocStatusInfo()
    else:
      self.available = 0
      self.status_info = localization_msg.msg.LocStatusInfo()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2QB().pack(_x.available, _x.status_info.quality, _x.status_info.common, _x.status_info.extended, _x.status_info.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.status_info is None:
        self.status_info = localization_msg.msg.LocStatusInfo()
      end = 0
      _x = self
      start = end
      end += 19
      (_x.available, _x.status_info.quality, _x.status_info.common, _x.status_info.extended, _x.status_info.type,) = _get_struct_2B2QB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2QB().pack(_x.available, _x.status_info.quality, _x.status_info.common, _x.status_info.extended, _x.status_info.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.status_info is None:
        self.status_info = localization_msg.msg.LocStatusInfo()
      end = 0
      _x = self
      start = end
      end += 19
      (_x.available, _x.status_info.quality, _x.status_info.common, _x.status_info.extended, _x.status_info.type,) = _get_struct_2B2QB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2QB = None
def _get_struct_2B2QB():
    global _struct_2B2QB
    if _struct_2B2QB is None:
        _struct_2B2QB = struct.Struct("<2B2QB")
    return _struct_2B2QB
