# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization_msg/LocStatusInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LocStatusInfo(genpy.Message):
  _md5sum = "8a36372e498de5e2ada620a2c8844ac6"
  _type = "localization_msg/LocStatusInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 quality
uint64 common
uint64 extended
uint8 type"""
  __slots__ = ['quality','common','extended','type']
  _slot_types = ['uint8','uint64','uint64','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       quality,common,extended,type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocStatusInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.quality is None:
        self.quality = 0
      if self.common is None:
        self.common = 0
      if self.extended is None:
        self.extended = 0
      if self.type is None:
        self.type = 0
    else:
      self.quality = 0
      self.common = 0
      self.extended = 0
      self.type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2QB().pack(_x.quality, _x.common, _x.extended, _x.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.quality, _x.common, _x.extended, _x.type,) = _get_struct_B2QB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2QB().pack(_x.quality, _x.common, _x.extended, _x.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.quality, _x.common, _x.extended, _x.type,) = _get_struct_B2QB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2QB = None
def _get_struct_B2QB():
    global _struct_B2QB
    if _struct_B2QB is None:
        _struct_B2QB = struct.Struct("<B2QB")
    return _struct_B2QB
