# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization_msg/LocPosition.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import localization_msg.msg

class LocPosition(genpy.Message):
  _md5sum = "50805a3c03e9264464f9b0b6c37b9360"
  _type = "localization_msg/LocPosition"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 available
LocPosGlobal position_global
LocPosLocal position_local
================================================================================
MSG: localization_msg/LocPosGlobal
float64 x
float64 y
float64 z
================================================================================
MSG: localization_msg/LocPosLocal
float64 x
float64 y
float64 z"""
  __slots__ = ['available','position_global','position_local']
  _slot_types = ['uint8','localization_msg/LocPosGlobal','localization_msg/LocPosLocal']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       available,position_global,position_local

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocPosition, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.available is None:
        self.available = 0
      if self.position_global is None:
        self.position_global = localization_msg.msg.LocPosGlobal()
      if self.position_local is None:
        self.position_local = localization_msg.msg.LocPosLocal()
    else:
      self.available = 0
      self.position_global = localization_msg.msg.LocPosGlobal()
      self.position_local = localization_msg.msg.LocPosLocal()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.available, _x.position_global.x, _x.position_global.y, _x.position_global.z, _x.position_local.x, _x.position_local.y, _x.position_local.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position_global is None:
        self.position_global = localization_msg.msg.LocPosGlobal()
      if self.position_local is None:
        self.position_local = localization_msg.msg.LocPosLocal()
      end = 0
      _x = self
      start = end
      end += 49
      (_x.available, _x.position_global.x, _x.position_global.y, _x.position_global.z, _x.position_local.x, _x.position_local.y, _x.position_local.z,) = _get_struct_B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.available, _x.position_global.x, _x.position_global.y, _x.position_global.z, _x.position_local.x, _x.position_local.y, _x.position_local.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position_global is None:
        self.position_global = localization_msg.msg.LocPosGlobal()
      if self.position_local is None:
        self.position_local = localization_msg.msg.LocPosLocal()
      end = 0
      _x = self
      start = end
      end += 49
      (_x.available, _x.position_global.x, _x.position_global.y, _x.position_global.z, _x.position_local.x, _x.position_local.y, _x.position_local.z,) = _get_struct_B6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B6d = None
def _get_struct_B6d():
    global _struct_B6d
    if _struct_B6d is None:
        _struct_B6d = struct.Struct("<B6d")
    return _struct_B6d
