# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hdas_msg/Drivetrain.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Drivetrain(genpy.Message):
  _md5sum = "0a54847f1086c67159c1bb023398666f"
  _type = "hdas_msg/Drivetrain"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 vel_fl
float32 vel_fr
float32 vel_r
float32 angle_fl
float32 angle_fr
float32 angle_r"""
  __slots__ = ['vel_fl','vel_fr','vel_r','angle_fl','angle_fr','angle_r']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vel_fl,vel_fr,vel_r,angle_fl,angle_fr,angle_r

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Drivetrain, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vel_fl is None:
        self.vel_fl = 0.
      if self.vel_fr is None:
        self.vel_fr = 0.
      if self.vel_r is None:
        self.vel_r = 0.
      if self.angle_fl is None:
        self.angle_fl = 0.
      if self.angle_fr is None:
        self.angle_fr = 0.
      if self.angle_r is None:
        self.angle_r = 0.
    else:
      self.vel_fl = 0.
      self.vel_fr = 0.
      self.vel_r = 0.
      self.angle_fl = 0.
      self.angle_fr = 0.
      self.angle_r = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.vel_fl, _x.vel_fr, _x.vel_r, _x.angle_fl, _x.angle_fr, _x.angle_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.vel_fl, _x.vel_fr, _x.vel_r, _x.angle_fl, _x.angle_fr, _x.angle_r,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.vel_fl, _x.vel_fr, _x.vel_r, _x.angle_fl, _x.angle_fr, _x.angle_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.vel_fl, _x.vel_fr, _x.vel_r, _x.angle_fl, _x.angle_fr, _x.angle_r,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
