(cl:in-package localization_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          META-VAL
          META
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          ORIENTATION-VAL
          ORIENTATION
          ACCELERATION-VAL
          ACCELERATION
          POSITION_STD-VAL
          POSITION_STD
          VELOCITY_STD-VAL
          VELOCITY_STD
          ANGULAR_VELOCITY_STD-VAL
          ANGULAR_VELOCITY_STD
          ORIENTATION_STD-VAL
          ORIENTATION_STD
          ACCELERATION_STD-VAL
          ACCELERATION_STD
          STATUS-VAL
          STATUS
          TRANSFORM-VAL
          TRANSFORM
          POSE_DETAIL-VAL
          POSE_DETAIL
          ROAD_LANE_ID_INFO-VAL
          ROAD_LANE_ID_INFO
          RESERVED-VAL
          RESERVED
))