    /gazebo_ros_control:
      pid_gains:
        steer_fl_joint:
          p: 100.0
          i: 15.0
          d: 10.0
          antiwindup: 1
        steer_fr_joint:
          p: 100.0
          i: 15.0
          d: 10.0
          antiwindup: 1
        steer_rl_joint:
          p: 100.0
          i: 15.0
          d: 10.0
          antiwindup: 1
        steer_rr_joint:
          p: 100.0
          i: 15.0
          d: 10.0
          antiwindup: 1

        wheel_fl_joint:
          p: 0.5
          i: 0.1
          d: 0.02
        wheel_fr_joint:
          p: 0.5
          i: 0.1
          d: 0.02
        wheel_rl_joint:
          p: 0.5
          i: 0.1
          d: 0.02
        wheel_rr_joint:
          p: 0.5
          i: 0.1
          d: 0.02

        seg1_to_seg2:
          p: 50
          i: 1
          d: 2
        seg2_to_seg3:
          p: 100
          i: 10
          d: 20
        seg3_to_seg4:
          p: 50
          i: 10
          d: 10
        seg4_to_seg5:
          p: 50
          i: 1
          d: 0.2
        seg5_to_seg6:
          p: 50
          i: 1
          d: 2
        seg6_to_seg7:
          p: 20
          i: 1
          d: 0.1

        finger1_joint:
          p: 5
          i: .2
        
        finger2_joint:
          p: 5
          i: .2